import type { NextPage } from 'next';
import Head from 'next/head';
import tw, { styled } from 'twin.macro';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ConditionalButton isRed={false}>Conditional TwinMacro element with Styled Components</ConditionalButton>
      </main>
    </div>
  );
};

export default Home;

const ConditionalButton = styled.button(({ isRed }: { isRed: boolean }) => [
  isRed ? tw`bg-red-500 hover:bg-red-700` : tw`bg-blue-500 hover:bg-blue-700`,
  tw`
    text-white
    font-bold
    py-2
    px-4
    border
    border-black
    rounded
  `,
]);
