import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import tw from 'twin.macro';
import CategoryForm from '../components/CategoryForm';

const Home: NextPage = () => {
  const [categories, setCategories] = useState<Category[] | []>([]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainSection>
        <CategoryForm setCategories={setCategories} />

        {categories.map((category) => (
          <div key={`${category.name} + ${category.spendingAmount}`}>
            <p>{category.name}</p>
            <p>{category.spendingAmount}</p>
          </div>
        ))}
      </MainSection>
    </>
  );
};

export default Home;

const MainSection = tw.main`
  flex
  flex-col
  h-screen
  justify-center
  items-center
`;
