import type { NextPage } from 'next';
import Head from 'next/head';
import tw from 'twin.macro';
import styled from 'styled-components';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Hello world with Tailwind CSS Set-up!</h1>
        <StyledButton>This is a button from Styled Components</StyledButton>
        <TailwindButton>This is a button from TwinMacro</TailwindButton>
        <ConditionalButton isRed={false}>Conditional TwinMacro element with Styled Components</ConditionalButton>
      </main>
    </div>
  );
};

export default Home;

const StyledButton = styled.button`
  background: red;
  color: white;
  font-size: 1em;
  text-align: center;
  padding: 0.25em 1em;
  border: 2px solid black;
`;

const TailwindButton = tw.button`
  bg-red-500
  hover:bg-red-700
  text-white
  font-bold
  py-2
  px-4
  border
  border-black
  rounded
`;

const ConditionalButton = styled.button(({ isRed }: { isRed: boolean }) => [
  isRed ? tw`bg-red-500 hover:bg-red-700` : tw`bg-blue-500 hover:bg-blue-700`,
  tw`
    text-white
    font-bold
    py-2
    px-4
    border
    border-black
    rounded
  `,
]);
